language: python
python:
  - 2.7

# safelist branch to build
branches:
  only:
    - master

services:
  - docker

env:
  - BROKER_URI=amqp://infrabbit:infrabbit@$localhost/

before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - docker run -d --hostname infrabbit --name infrabbit -e RABBITMQ_DEFAULT_USER=infrabbit -e RABBITMQ_DEFAULT_PASS=infrabbit -p 15672:15672 -p 5672:5672 aleasoluciones/rabbitmq-delayed-message:0.2

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - sleep 20
  - ./dev/unit_tests.sh
  - ./dev/integration_tests_for_travis.sh

notifications:
  email:
    - bifer@alea-soluciones.com
