language: python
python:
  - 2.7

services:
  - rabbitmq

env:
  - BROKER_URI=amqp://guest:guest@localhost/

install:
  - python setup.py develop
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - nosetests tests integration_tests
