language: python
python:
  - 2.7

services:
  - rabbitmq

env:
  - BROKER_URI=amqp://guest:guest@localhost/

before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

install:
  - python setup.py develop
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - nosetests tests integration_tests
